# Generated by Django 5.1.7 on 2025-04-21 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='auth_app.vendor'),
        ),
        migrations.AddField(
            model_name='notification',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='auth_app.vendor'),
        ),
        migrations.AddField(
            model_name='menu',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='auth_app.vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='foodlisting',
            unique_together={('menu', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('vendor', 'name')},
        ),
    ]
