# Generated by Django 5.1.7 on 2025-04-23 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_foodlisting_menu'),
        ('customer_app', '0003_rename_date_joined_customer_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='password',
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_listings', to='auth_app.vendor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customer_app.customer'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
